name: 'hugo-with-github-issues'
description: 'Convert github issues to markdowns'
branding:
  icon: 'archive'
  color: 'blue'
inputs:
  github-token:
    description: 'github token'
    required: true
  repo:
    description: 'repo to export'
    required: true
  owner:
    description: 'repo owner'
    required: true
  skip-author:
    description: 'skip issue written by the skip-author'
    required: false
  issue-state:
    description: 'export issues only in state(open or closed)'
    required: true
    default: 'all'
  use-issue-seperator:
    description: 'use seperator among comments'
    required: true
    default: 'false'
  skip-pull-requests:
    description: 'skip pull requests issues'
    required: true
    default: 'false'
  output:
    description: 'destination folder to store markdown files'
    required: true
    default: 'content'
runs:
  using: 'node12'
  main: 'dist/index.js'
